title: General Policy Evaluation and Improvement by Learning to Identify Few But Crucial States
logo: /assets/img/evaluator_architecture_diagram.png
description: Francesco Faccio, Vincent Herrmann, Aditya Ramesh, Louis Kirsch, JÃ¼rgen Schmidhuber
show_downloads: false
google_analytics: false
theme: jekyll-theme-minimal
